### ISSUE TITLE
DockerHub image seems outdated

### ISSUE THREAD

**Issue by gy-mate** [amandasaurus/osm-mapping-party-before-after#10]
The [`gedankenstuecke/osm-mapping-party-before-after`](https://hub.docker.com/r/gedankenstuecke/osm-mapping-party-before-after) Docker image was last updated on 2024-12-19 on DockerHub. However, the last commit on the `main` branch was on 2024-12-28.
(Automating updates is theoretically possible using https://github.com/marketplace/actions/build-and-push-docker-images.)

Furthermore, the instructions on DockerHub seem incomplete to me:

> Once the docker container is running, you can connect into it to get a bash inside to run the commands as outlined below

But when I click on _Start_ in the Docker Desktop app the container immediately stops so I cannot enter it.

Maybe moving the instructions to this repo's README and just leaving the reference would be a better solution. It would also allow direct contributions.

**Comment by gedankenstuecke** [comment]
Great catch, thanks, I indeed totally forgot to push the latest version, which is now fixed! I've also simplified the README there! 

I'll make a new issue for automating the image pushing to hopefully get to that in the new year. Until then: have a lovely new year/"Guten Rutsch" as the Germans say!

**Comment by gy-mate** [comment]
@gedankenstuecke Thanks a lot and a Happy New Year to you too! :)
