### ISSUE TITLE
'Invalid build token' error when opening the MyBinder version

### ISSUE THREAD

**Issue by gy-mate** [amandasaurus/osm-mapping-party-before-after#9]
1. Open https://mybinder.org/v2/gh/amandasaurus/osm-mapping-party-before-after/main?labpath=make-images.ipynb in Safari `18.2`
2. See the following error in the MyBinder build logs:
    <img width="1510" alt="Invalid build token" src="https://github.com/user-attachments/assets/0f1e4a9e-ba82-4fbb-8cfa-c9476272bb24" />

_Possibly related to https://github.com/jupyterhub/binderhub/issues/1455._

**Comment by gedankenstuecke** [comment]
Let's see, I'm using Firefox and it seems to build so far! Did it immediately crash for you?

**Comment by gy-mate** [comment]
Yes, immediately.

Weird, but _enabling_ cross-origin restrictions in the browser settings fixed the problem! (Disabling it again produces the same issue.)

**Comment by gedankenstuecke** [comment]
That’s strange! But glad you found a work around!
